baseurl = "/"
title = "The Triple Mando"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "THE TRIPLE MANDO"
    description = "musings, ramblings, and the occasional good idea about the game of disc golf"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
